language: node_js
cache:
  directories:
  - node_modules
  -~/.npm
node_js:
- '12'
git:
  depth: 3
deploy:
  provider: pages
  kip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: ./
  target_branch: gh-pages
  commit_message: "deploy del proyecto"
    on:
    branch: master